URL_SEFAZ = "https://cdwfazenda.paas.pr.gov.br/cdwportal/certidao/automatica"

TIMEOUT_EMISSAO = 60

TEMPO_ESPERA_MINIMO = 8
TEMPO_ESPERA_MAXIMO = 15

TEMPO_RETRY_MINIMO = 10
TEMPO_RETRY_MAXIMO = 20

TEMPO_CARREGAMENTO_PAGINA = 5
TEMPO_APOS_COOKIES = 2
TEMPO_APOS_PREENCHER_DOCUMENTO = 1
TEMPO_APOS_CLICAR_EMITIR = 5
TEMPO_ANTES_BAIXAR_PDF = 3
TEMPO_AGUARDAR_DOWNLOAD_PDF = 15
TEMPO_APOS_FECHAR_BROWSER = 3

DEBUG = True