import os

from dotenv import load_dotenv

load_dotenv()

URL_SEFAZ = "https://cdwfazenda.paas.pr.gov.br/cdwportal/certidao/automatica"

TIMEOUT_EMISSAO = int(os.getenv("TIMEOUT_EMISSAO", 60))

TEMPO_ESPERA_MINIMO = 8
TEMPO_ESPERA_MAXIMO = 15

TEMPO_RETRY_MINIMO = 10
TEMPO_RETRY_MAXIMO = 20

TEMPO_CARREGAMENTO_PAGINA = 5
TEMPO_APOS_COOKIES = 2
TEMPO_APOS_PREENCHER_DOCUMENTO = 1
TEMPO_APOS_CLICAR_EMITIR = 5
TEMPO_ANTES_BAIXAR_PDF = 3
TEMPO_AGUARDAR_DOWNLOAD_PDF = 15
TEMPO_APOS_FECHAR_BROWSER = 3

TEMPO_ANTES_DIGITAR_MINIMO = 1.5
TEMPO_ANTES_DIGITAR_MAXIMO = 3.5

TEMPO_ENTRE_TECLAS_MINIMO = 0.1
TEMPO_ENTRE_TECLAS_MAXIMO = 0.4

TOTAL_TENTATIVAS_PDF = 20
TEMPO_ESPERA_PDF = 1

TOTAL_TENTATIVAS_EMISSAO = 3

TEMPO_PAUSA_BLOQUEIO = int(os.getenv("TEMPO_PAUSA_BLOQUEIO", 300))

DEBUG = os.getenv("DEBUG", "False") == "True"